spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.key.deserializer= org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset= earliest
spring.kafka.consumer.value.deserializer= org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.bootstrap-servers= localhost:9092
spring.kafka.producer.key.deserializer= org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value.deserializer= org.apache.kafka.common.serialization.StringSerializer
server.port=5051

grpc.client.userdbservice.address=static://localhost:1010
grpc.client.userdbservice.negotiationType=plaintext

grpc.client.NService.address=static://localhost:2010
grpc.client.NService.negotiationType=plaintext

grpc.client.CService.address=static://localhost:3010
grpc.client.CService.negotiationType=plaintext

grpc.client.sessionService.address=static://localhost:2029
grpc.client.sessionService.negotiationType=plaintext